---
apiVersion: v1
kind: Service
metadata:
  name: scaler-service
spec:
  selector:
    app: scaler
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
      name: grpc
    - protocol: TCP
      port: 8501
      targetPort: 8501
      name: rest
