apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaler-deployment
  labels:
    app: scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaler
  template:
    metadata:
      labels:
        app: scaler
    spec:
      imagePullSecrets:
        - name: harbor-creds
      containers:
        - name: scaler
          image: 10.124.69.3:30444/toolchains/tensorflow-serving:20221229-bilstm_multistep
          imagePullPolicy: Always
          ports:
            - containerPort: 8500
            - containerPort: 8501
