apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app.kubernetes.io/name: booking-app
  ports:
    - name: p5003
      protocol: TCP
      port: 5003
      targetPort: 5003

---
apiVersion: v1
kind: Service
metadata:
  name: movies-service
spec:
  selector:
    app.kubernetes.io/name: movies-app
  ports:
    - name: p5001
      protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: showtimes-service
spec:
  selector:
    app.kubernetes.io/name: showtimes-app
  ports:
    - name: p5002
      protocol: TCP
      port: 5002
      targetPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app.kubernetes.io/name: user-app
  ports:
    - name: p5004
      protocol: TCP
      port: 5004
      targetPort: 5004
